batch_size: 64

dataset: 'mnist' # cifar10
attack_method: ''
gpu_num: "3"


# model.py 참조
model_name: 'mnist_cnn'


ttest_model: 'ttest_model' #########################

# model_train: 'cifar_vgg16' 

attack_eps: 

xai_method: ''